<!-- Copyright © 2026 DevAM. Licensed under the MIT License. See LICENSE in the repository root. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NetworkInspector.Filter.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetworkInspector.Filter\NetworkInspector.Filter.csproj" />
    <ProjectReference Include="..\NetworkInspector.Core\NetworkInspector.Core.csproj" />
    <ProjectReference Include="..\NetworkInspector.Protocols\NetworkInspector.Protocols.csproj" />
  </ItemGroup>
</Project>
