// Copyright © 2026 DevAM. Licensed under the MIT License. See LICENSE in the repository root.

using NetworkInspector.Core;

namespace NetworkInspector.Sources.Random;

/// <summary>
/// A synthetic frame source that generates random, well-formed network frames entirely in memory.
/// <para>
/// <b>Design principles:</b>
/// <list type="bullet">
///   <item>
///     <b>Per-frame determinism</b> — each frame is seeded from
///     <see cref="Xoroshiro128PlusPlus.DeriveFrameSeed"/><c>(masterSeed, frameIndex)</c>,
///     so any frame can be regenerated by index without producing all prior frames.
///   </item>
///   <item>
///     <b>Fill-then-patch</b> — the entire frame buffer is first filled with random bytes
///     via the SIMD-accelerated <see cref="Xoroshiro128PlusPlus.FillBytes"/>, then only the
///     required protocol header fields are overwritten.  This minimises RNG calls and keeps
///     memory access sequential.
///   </item>
///   <item>
///     <b>SIMD acceleration</b> — <see cref="Xoroshiro128PlusPlus.FillBytes"/> dispatches to
///     AVX2 (32 bytes/cycle), SSE2/NEON (16 bytes/cycle), or a 32-byte-unrolled scalar
///     fallback at runtime.
///   </item>
/// </list>
/// All <see cref="RandomFrameMode"/> values are supported: eight Ethernet-based modes
/// (including TCP single-segment and TCP stream modes) and two CAN bus modes
/// (classic CAN and CAN FD in SocketCAN format).
/// </para>
/// </summary>
/// <remarks>
/// Creates a random frame source with explicit options.
/// </remarks>
/// <param name="options">Configuration (frame count, mode, seed, size range, etc.).</param>
/// <param name="uiName">
/// Optional display name.  When <c>null</c>, a name is derived from the options.
/// </param>
public sealed class RandomFrameSource(RandomSourceOptions options, string? uiName = null) : IFrameSource
{
    #region Constants

    // ─── Protocol constants ───────────────────────────────────────────────────

    /// <summary>Ethernet II EtherType for IPv4.</summary>
    private const ushort EtherTypeIPv4 = 0x0800;

    /// <summary>Ethernet II EtherType for IPv6.</summary>
    private const ushort EtherTypeIPv6 = 0x86DD;

    /// <summary>IPv4 header Version (4) + IHL (5 = 20 bytes) packed into one byte.</summary>
    private const byte IPv4VersionIhl = 0x45;

    /// <summary>IP protocol number for UDP.</summary>
    private const byte IpProtoUdp = 17;

    /// <summary>Ethernet header size.</summary>
    private const int EthHeaderSize = 14;  // bytes

    /// <summary>IPv4 header size (no options).</summary>
    private const int IPv4HeaderSize = 20; // bytes

    /// <summary>IPv6 fixed header size.</summary>
    private const int IPv6HeaderSize = 40; // bytes

    /// <summary>UDP header size.</summary>
    private const int UdpHeaderSize = 8;   // bytes

    /// <summary>SocketCAN header size (ID + DLC + flags + reserved).</summary>
    private const int SocketCanHeaderSize = 8; // bytes

    /// <summary>Classic CAN fixed data area size.</summary>
    private const int CanClassicDataSize = 8; // bytes

    /// <summary>SocketCAN Extended Frame Format flag (bit 31 of ID field).</summary>
    private const uint SocketCanEff = 0x80000000;

    /// <summary>SocketCAN FD Format indicator flag (byte 5, bit 2).</summary>
    private const byte SocketCanFdFdf = 0x04;

    /// <summary>SocketCAN Bit Rate Switch flag (byte 5, bit 0).</summary>
    private const byte SocketCanFdBrs = 0x01;

    /// <summary>IP protocol number for TCP.</summary>
    private const byte IpProtoTcp = 6;

    /// <summary>TCP header size (no options).</summary>
    private const int TcpHeaderSize = 20; // bytes

    /// <summary>CAN FD DLC-to-data-length mapping (indices 0–15).</summary>
    private static ReadOnlySpan<byte> CanFdDlcToLength =>
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 12, 16, 20, 24, 32, 48, 64];

    #endregion

    #region Fields

    // ─── Configuration ────────────────────────────────────────────────────────

    /// <summary>Resolved options (never null after construction). Validated eagerly so
    /// invalid options surface at construction time, matching <c>BlfSource.Open</c> /
    /// <c>PcapSource.Open</c>.</summary>
    private readonly RandomSourceOptions _Options = ValidateOptions(options);

    /// <summary>Resolved master seed (derived from options or entropy at Start time).</summary>
    private ulong _MasterSeed;

    /// <summary>Resolved base timestamp (derived from options or wall clock at Start time).</summary>
    private Timestamp _BaseTimestamp;

    /// <summary>User-friendly source name.</summary>
    private readonly string _UiName = uiName ?? BuildDefaultName(options);

    // ─── Runtime state ────────────────────────────────────────────────────────

    /// <summary>Zero-based index of the next frame to produce.</summary>
    private int _FrameIndex;

    /// <summary>Whether <see cref="Start"/> has been called.</summary>
    private bool _Started;

    /// <summary>Whether this instance has been disposed.</summary>
    private bool _Disposed;

    /// <summary>Registry supplied by Start.</summary>
    private FrameInterfaceRegistry? _Registry;

    /// <summary>Source ID assigned in Start.</summary>
    private FrameSourceId _SourceId;

    /// <summary>Ethernet interface registered in Start.</summary>
    private FrameInterfaceId _InterfaceId;

    /// <summary>Precomputed frame layout for TCP stream modes (null for other modes).</summary>
    private TcpStreamLayout? _TcpStreamLayout;

    #endregion

    #region Constructors

    /// <summary>
    /// Creates a random frame source with a specific mode, count, and seed.
    /// Convenience overload for the most common call sites.
    /// </summary>
    /// <param name="count">Total frames to generate (0 = unlimited).</param>
    /// <param name="seed">Master PRNG seed for reproducibility.</param>
    /// <param name="mode">Frame generation mode.</param>
    /// <param name="uiName">Optional display name.</param>
    public RandomFrameSource(
        int count = 0,
        ulong seed = 42,
        RandomFrameMode mode = RandomFrameMode.UdpIPv4,
        string? uiName = null)
        : this(new RandomSourceOptions { FrameCount = count, Seed = seed, Mode = mode }, uiName)
    {
    }

    #endregion

    #region IFrameSource Implementation

    // ─── IFrameSource ─────────────────────────────────────────────────────────

    /// <inheritdoc/>
    public string UiName => _UiName;

    /// <inheritdoc/>
    public string? Description =>
        $"Synthetic random frame source — mode={_Options.Mode}, " +
        $"seed={(_Options.Seed.HasValue ? _Options.Seed.Value.ToString() : (Volatile.Read(ref _Started) ? _MasterSeed.ToString() : "<entropy>"))}, " +
        $"count={_Options.FrameCount}";

    /// <inheritdoc/>
    public int? EstimatedFrameCount =>
        _TcpStreamLayout is { } layout
            ? (_Options.FrameCount > 0 ? Math.Min(_Options.FrameCount, layout.TotalFrameCount) : layout.TotalFrameCount)
            : (_Options.FrameCount > 0 ? _Options.FrameCount : null);

    /// <inheritdoc/>
    public bool IsRunning => Volatile.Read(ref _Started) && !Volatile.Read(ref _Disposed);

    /// <inheritdoc/>
    public void Start(FrameSourceId sourceId, FrameInterfaceRegistry registry)
    {
        ObjectDisposedException.ThrowIf(Volatile.Read(ref _Disposed), this);
        ArgumentNullException.ThrowIfNull(registry);

        // Options were validated at construction time; re-validate is unnecessary.

        _SourceId = sourceId;
        _Registry = registry;
        _FrameIndex = 0;

        // Resolve seed: use configured value or derive from system entropy
        _MasterSeed = _Options.Seed ?? DeriveEntropySeed();

        // Resolve base timestamp: use configured value or current wall clock
        _BaseTimestamp = _Options.BaseTimestamp ?? CurrentTimestamp();

        // Register an interface matching the frame mode's link type
        LinkType linkType = LinkTypeForMode(_Options.Mode);
        string ifName = IsCanMode(_Options.Mode) ? "can0" : "eth0";
        string ifDescr = IsCanMode(_Options.Mode)
            ? "Synthetic SocketCAN interface"
            : "Synthetic Ethernet interface";
        _InterfaceId = registry.Register(sourceId, ifName, ifDescr, linkType);

        // Precompute layout for TCP stream modes (stateless — no mutable generator)
        if (_Options.Mode is RandomFrameMode.TcpStreamIPv4 or RandomFrameMode.TcpStreamIPv6)
        {
            _TcpStreamLayout = new TcpStreamLayout(_Options.TcpStreamOptions);
        }

        Volatile.Write(ref _Started, true);
    }

    /// <inheritdoc/>
    public Frame? NextFrame()
    {
        ObjectDisposedException.ThrowIf(Volatile.Read(ref _Disposed), this);

        if (!Volatile.Read(ref _Started))
        {
            throw new InvalidOperationException("RandomFrameSource.Start() must be called before NextFrame().");
        }

        // Read _FrameIndex via Volatile.Read so that any compiler or JIT
        // reordering of the load relative to the _Started/_Disposed checks above is
        // prevented.  The increment uses Volatile.Write for the same reason, and for
        // consistency with other IFrameSource implementations in this codebase.
        int currentIndex = Volatile.Read(ref _FrameIndex);

        if (_Options.FrameCount > 0 && currentIndex >= _Options.FrameCount)
        {
            return null;
        }

        // TCP stream modes use stateless layout-based generation
        if (_TcpStreamLayout is { } layout)
        {
            if (currentIndex >= layout.TotalFrameCount)
            {
                return null;
            }

            bool isIpv6 = _Options.Mode == RandomFrameMode.TcpStreamIPv6;
            byte[]? streamData = TcpStreamFrameBuilder.BuildFrame(
                in layout, _Options.TcpStreamOptions, _MasterSeed, currentIndex, isIpv6);

            if (streamData is null)
            {
                return null;
            }

            Timestamp timestamp = new(_BaseTimestamp.AsNanos + (currentIndex * _Options.TimestampInterval));
            ParseResult<Frame> streamResult = Frame.Create(
                new FrameId(currentIndex),
                timestamp,
                streamData,
                LinkTypeForMode(_Options.Mode),
                _InterfaceId,
                _Registry!);

            if (!streamResult.IsSuccess)
            {
                throw new InvalidOperationException(
                    $"RandomFrameSource failed to create TCP stream frame at index {currentIndex}: {streamResult.Error}");
            }

            Volatile.Write(ref _FrameIndex, currentIndex + 1);
            return streamResult.Value;
        }

        Frame frame = GenerateFrameByIndex(currentIndex);
        Volatile.Write(ref _FrameIndex, currentIndex + 1);
        return frame;
    }

    /// <inheritdoc/>
    public void Dispose()
    {
        if (Volatile.Read(ref _Disposed))
        {
            return;
        }

        Volatile.Write(ref _Disposed, true);
        // _Started intentionally left set: it is a one-shot "has Start been called"
        // latch (see SOURCE_GUIDE §13.3). IsRunning combines it with !_Disposed.
        // Clear the registry reference so the session can be GC'd after Dispose().
        _Registry = null;

        GC.SuppressFinalize(this);
    }

    #endregion

    #region Private Helpers

    // ─── Frame generation ─────────────────────────────────────────────────────

    /// <summary>
    /// Generates and wraps a single frame for the given zero-based <paramref name="index"/>.
    /// <para>
    /// The per-frame PRNG seed is derived via
    /// <see cref="Xoroshiro128PlusPlus.DeriveFrameSeed"/> so the same index always produces
    /// the same frame bytes regardless of call order.
    /// </para>
    /// </summary>
    /// <exception cref="InvalidOperationException">Frame creation unexpectedly failed.</exception>
    private Frame GenerateFrameByIndex(int index)
    {
        ulong frameSeed = Xoroshiro128PlusPlus.DeriveFrameSeed(_MasterSeed, (uint)index);
        Xoroshiro128PlusPlus rng = new(frameSeed);

        // Determine frame size depending on mode.
        // CAN classic is always exactly 16 bytes.
        // CAN FD picks a random DLC first, then sizes the buffer from the FD length table.
        // All other modes use the configurable [min, max] range.
        int frameSize;
        byte canFdDlc = 0; // only meaningful for CanFd mode
        if (_Options.Mode == RandomFrameMode.Can)
        {
            // Classic CAN: fixed 16 bytes (8-byte header + 8-byte data)
            frameSize = SocketCanHeaderSize + CanClassicDataSize;
        }
        else if (_Options.Mode == RandomFrameMode.CanFd)
        {
            // CAN FD: random DLC 0–15 → variable data length
            canFdDlc = (byte)(rng.NextU64() % 16);
            int dataLen = CanFdDlcToLength[canFdDlc];
            frameSize = SocketCanHeaderSize + dataLen;
        }
        else
        {
            int minSize = MinSizeForMode(_Options.Mode, _Options.MinFrameSize);
            int maxSize = Math.Max(minSize, _Options.MaxFrameSize);
            frameSize = rng.NextRange(minSize, maxSize + 1); // bytes
        }

        byte[] data = new byte[frameSize];

        // Fill then patch — bulk-fill with random bytes, then fix protocol fields
        switch (_Options.Mode)
        {
            case RandomFrameMode.FullRandom:
                GenerateFullRandom(ref rng, data);
                break;
            case RandomFrameMode.Ethernet:
                GenerateEthernet(ref rng, data);
                break;
            case RandomFrameMode.IPv4:
                GenerateIPv4(ref rng, data);
                break;
            case RandomFrameMode.IPv6:
                GenerateIPv6(ref rng, data);
                break;
            case RandomFrameMode.UdpIPv4:
                GenerateUdpIPv4(ref rng, data);
                break;
            case RandomFrameMode.UdpIPv6:
                GenerateUdpIPv6(ref rng, data);
                break;
            case RandomFrameMode.Can:
                GenerateCan(ref rng, data);
                break;
            case RandomFrameMode.CanFd:
                GenerateCanFd(ref rng, data, canFdDlc);
                break;
            case RandomFrameMode.TcpIPv4:
                GenerateTcpIPv4(ref rng, data);
                break;
            case RandomFrameMode.TcpIPv6:
                GenerateTcpIPv6(ref rng, data);
                break;
            default:
                throw new InvalidOperationException($"Unsupported RandomFrameMode: {_Options.Mode}");
        }

        // Timestamp: base + index × interval
        Timestamp timestamp = new(_BaseTimestamp.AsNanos + (index * _Options.TimestampInterval));

        ParseResult<Frame> result = Frame.Create(
            new FrameId(index),
            timestamp,
            data,
            LinkTypeForMode(_Options.Mode),
            _InterfaceId,
            _Registry!);

        if (!result.IsSuccess)
        {
            throw new InvalidOperationException(
                $"RandomFrameSource failed to create frame at index {index}: {result.Error}");
        }

        return result.Value;
    }

    // ─── Mode generators (fill-then-patch strategy) ───────────────────────────

    /// <summary>
    /// <b>FullRandom</b>: fill entire buffer — no protocol structure, fastest mode.
    /// </summary>
    // Single SIMD-accelerated bulk fill, nothing to patch
    private static void GenerateFullRandom(ref Xoroshiro128PlusPlus rng, byte[] data) =>
        rng.FillBytes(data);

    /// <summary>
    /// <b>Ethernet</b>: fill entire buffer with random bytes.
    /// MAC addresses and EtherType are already random — no patching needed.
    /// </summary>
    // All Ethernet fields (dst MAC, src MAC, EtherType) are random — nothing to patch
    private static void GenerateEthernet(ref Xoroshiro128PlusPlus rng, byte[] data) =>
        rng.FillBytes(data);

    /// <summary>
    /// <b>IPv4</b>: fill-then-patch.
    /// Random payload, addresses, and identification.  Patches version, IHL, lengths,
    /// DF flag, TTL, and header checksum.  Protocol is kept random (non-zero).
    /// </summary>
    private static void GenerateIPv4(ref Xoroshiro128PlusPlus rng, byte[] data)
    {
        rng.FillBytes(data);

        // Patch Ethernet EtherType
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(12), EtherTypeIPv4);

        int ip = EthHeaderSize;
        ushort totalLength = (ushort)(data.Length - EthHeaderSize); // bytes

        data[ip] = IPv4VersionIhl;          // Version 4, IHL 5 (20 bytes, no options)
        data[ip + 1] = 0;                        // DSCP + ECN = 0
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(ip + 2), totalLength);
        // Identification (ip+4, ip+5) already random
        data[ip + 6] = 0x40;  // DF flag, no MF, fragment offset = 0
        data[ip + 7] = 0x00;
        data[ip + 8] = 64;    // TTL = 64 hops
        // Protocol (ip+9) already random; clamp to non-zero
        if (data[ip + 9] == 0)
        {
            data[ip + 9] = 1;
        }
        // Clear checksum field before computing
        data[ip + 10] = 0;
        data[ip + 11] = 0;
        // Source IP (ip+12..ip+15): already random
        // Dest IP   (ip+16..ip+19): already random

        ushort checksum = CalculateIPv4Checksum(data, ip);
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(ip + 10), checksum);
    }

    /// <summary>
    /// <b>IPv6</b>: fill-then-patch.
    /// Random addresses and payload.  Patches EtherType, version nibble,
    /// payload length, and hop limit.  Next-header is kept random (non-zero).
    /// </summary>
    private static void GenerateIPv6(ref Xoroshiro128PlusPlus rng, byte[] data)
    {
        rng.FillBytes(data);

        // Patch Ethernet EtherType
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(12), EtherTypeIPv6);

        int ip = EthHeaderSize;
        ushort payloadLength = (ushort)(data.Length - EthHeaderSize - IPv6HeaderSize); // bytes

        // Patch version nibble (high 4 bits = 6), keep random Traffic Class + Flow Label
        data[ip] = (byte)((data[ip] & 0x0F) | 0x60);
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(ip + 4), payloadLength);
        // Next-header (ip+6) already random; clamp to non-zero
        if (data[ip + 6] == 0)
        {
            data[ip + 6] = 1;
        }
        data[ip + 7] = 64;  // Hop limit = 64
        // Source address (ip+8..ip+23):  already random
        // Dest address   (ip+24..ip+39): already random
    }

    /// <summary>
    /// <b>UdpIPv4</b>: fill-then-patch.
    /// Fully well-formed Ethernet/IPv4/UDP frame.  UDP checksum is set to 0
    /// (optional in IPv4 per RFC 768).
    /// </summary>
    private static void GenerateUdpIPv4(ref Xoroshiro128PlusPlus rng, byte[] data)
    {
        rng.FillBytes(data);

        // ── Ethernet header (0–13) ──
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(12), EtherTypeIPv4);

        int ip = EthHeaderSize;
        int udp = ip + IPv4HeaderSize;
        ushort totalLength = (ushort)(data.Length - EthHeaderSize); // bytes
        ushort udpLength = (ushort)(data.Length - udp);           // bytes

        // ── IPv4 header (ip..ip+19) ──
        data[ip] = IPv4VersionIhl;
        data[ip + 1] = 0;                        // DSCP + ECN = 0
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(ip + 2), totalLength);
        // Identification (ip+4, ip+5) already random
        data[ip + 6] = 0x40;  // DF
        data[ip + 7] = 0x00;
        data[ip + 8] = 64;    // TTL
        data[ip + 9] = IpProtoUdp;
        data[ip + 10] = 0;    // Checksum — clear before computing
        data[ip + 11] = 0;
        // Source IP (ip+12..ip+15): already random
        // Dest IP   (ip+16..ip+19): already random

        ushort checksum = CalculateIPv4Checksum(data, ip);
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(ip + 10), checksum);

        // ── UDP header (udp..udp+7) ──
        if (udpLength >= UdpHeaderSize && data.Length >= udp + UdpHeaderSize)
        {
            // Source port (udp+0, udp+1): already random
            // Dest port   (udp+2, udp+3): already random
            BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(udp + 4), udpLength);
            data[udp + 6] = 0;   // Checksum = 0 (disabled, valid for IPv4 per RFC 768)
            data[udp + 7] = 0;
            // Payload (udp+8..): already random
        }
    }

    /// <summary>
    /// <b>UdpIPv6</b>: fill-then-patch.
    /// Fully well-formed Ethernet/IPv6/UDP frame.  UDP checksum is set to 0.
    /// </summary>
    private static void GenerateUdpIPv6(ref Xoroshiro128PlusPlus rng, byte[] data)
    {
        rng.FillBytes(data);

        // ── Ethernet header (0–13) ──
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(12), EtherTypeIPv6);

        int ip = EthHeaderSize;
        int udp = ip + IPv6HeaderSize;
        ushort payloadLength = (ushort)(data.Length - ip - IPv6HeaderSize); // bytes
        ushort udpLength = (ushort)(data.Length - udp);                  // bytes

        // ── IPv6 header (ip..ip+39) ──
        data[ip] = (byte)((data[ip] & 0x0F) | 0x60);  // version = 6, keep TC/FL random
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(ip + 4), payloadLength);
        data[ip + 6] = IpProtoUdp;  // Next header = UDP
        data[ip + 7] = 64;          // Hop limit
        // Source address (ip+8..ip+23):  already random
        // Dest address   (ip+24..ip+39): already random

        // ── UDP header (udp..udp+7) ──
        if (udpLength >= UdpHeaderSize && data.Length >= udp + UdpHeaderSize)
        {
            // Source port (udp+0, udp+1): already random
            // Dest port   (udp+2, udp+3): already random
            BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(udp + 4), udpLength);
            data[udp + 6] = 0;   // Checksum = 0
            data[udp + 7] = 0;
            // Payload (udp+8..): already random
        }
    }

    /// <summary>
    /// <b>Can</b>: generates a classic CAN 2.0 frame in SocketCAN format (fixed 16 bytes).
    /// <para>
    /// Layout: <c>[id(4 BE) | dlc(1) | fd_flags(1) | reserved(2) | data(8)]</c>.
    /// A random 50/50 decision selects 11-bit (standard) or 29-bit (extended) ID.
    /// DLC is randomised 0–8.  Data area is always 8 bytes (padded with random bytes
    /// when DLC &lt; 8, matching real CAN bus behaviour).
    /// </para>
    /// </summary>
    private static void GenerateCan(ref Xoroshiro128PlusPlus rng, byte[] data)
    {
        // Fill entire 16-byte frame with random bytes first (data area gets random padding)
        rng.FillBytes(data);

        // ── ID field (bytes 0–3, big-endian) ──
        // Random decision: 50% standard (11-bit), 50% extended (29-bit)
        bool extended = (rng.NextU64() & 1) != 0;
        uint canId;
        if (extended)
        {
            // 29-bit ID with EFF flag set
            canId = (rng.NextU32() & 0x1FFFFFFF) | SocketCanEff;
        }
        else
        {
            // 11-bit standard ID
            canId = rng.NextU32() & 0x7FF;
        }
        BinaryPrimitives.WriteUInt32BigEndian(data.AsSpan(0), canId);

        // ── DLC (byte 4): random 0–8 ──
        data[4] = (byte)(rng.NextU64() % 9);

        // ── FD flags (byte 5): 0 for classic CAN ──
        data[5] = 0;

        // ── Reserved (bytes 6–7): must be zero ──
        data[6] = 0;
        data[7] = 0;

        // Data area (bytes 8–15) is already filled with random bytes from FillBytes
    }

    /// <summary>
    /// <b>CanFd</b>: generates a CAN FD frame in SocketCAN format (8-byte header + variable data).
    /// <para>
    /// Layout: <c>[id(4 BE) | dlc(1) | fd_flags(1) | reserved(2) | data(0–64)]</c>.
    /// A random 50/50 decision selects 11-bit (standard) or 29-bit (extended) ID.
    /// The <paramref name="dlc"/> is pre-determined by the caller so the buffer is already
    /// sized correctly.  FDF and BRS flags are set.
    /// </para>
    /// </summary>
    private static void GenerateCanFd(ref Xoroshiro128PlusPlus rng, byte[] data, byte dlc)
    {
        // Fill entire frame with random bytes first (data area gets random content)
        rng.FillBytes(data);

        // ── ID field (bytes 0–3, big-endian) ──
        bool extended = (rng.NextU64() & 1) != 0;
        uint canId;
        if (extended)
        {
            canId = (rng.NextU32() & 0x1FFFFFFF) | SocketCanEff;
        }
        else
        {
            canId = rng.NextU32() & 0x7FF;
        }
        BinaryPrimitives.WriteUInt32BigEndian(data.AsSpan(0), canId);

        // ── DLC (byte 4): supplied by caller ──
        data[4] = dlc;

        // ── FD flags (byte 5): FDF + BRS set ──
        data[5] = SocketCanFdFdf | SocketCanFdBrs;

        // ── Reserved (bytes 6–7): must be zero ──
        data[6] = 0;
        data[7] = 0;

        // Data area (bytes 8..) is already filled with random bytes from FillBytes
    }

    /// <summary>
    /// <b>TcpIPv4</b>: fill-then-patch.
    /// Fully well-formed Ethernet/IPv4/TCP segment. Random addresses, ports,
    /// sequence/ack numbers, and payload. ACK+PSH flags set by default.
    /// TCP checksum is set to 0 (no pseudo-header computation for simplicity).
    /// </summary>
    private static void GenerateTcpIPv4(ref Xoroshiro128PlusPlus rng, byte[] data)
    {
        rng.FillBytes(data);

        // ── Ethernet header (0–13) ──
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(12), EtherTypeIPv4);

        int ip = EthHeaderSize;
        int tcp = ip + IPv4HeaderSize;
        ushort totalLength = (ushort)(data.Length - EthHeaderSize); // bytes

        // ── IPv4 header ──
        data[ip] = IPv4VersionIhl;
        data[ip + 1] = 0;
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(ip + 2), totalLength);
        data[ip + 6] = 0x40;  // DF
        data[ip + 7] = 0x00;
        data[ip + 8] = 64;    // TTL
        data[ip + 9] = IpProtoTcp;
        data[ip + 10] = 0;
        data[ip + 11] = 0;

        ushort checksum = CalculateIPv4Checksum(data, ip);
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(ip + 10), checksum);

        // ── TCP header (tcp..tcp+19) ──
        if (data.Length >= tcp + TcpHeaderSize)
        {
            // Src port (tcp+0,+1): already random
            // Dst port (tcp+2,+3): already random
            // Seq number (tcp+4..+7): already random
            // Ack number (tcp+8..+11): already random
            data[tcp + 12] = 0x50;  // Data offset = 5 (20 bytes), no reserved bits
            data[tcp + 13] = 0x18;  // ACK + PSH flags
            // Window (tcp+14,+15): already random
            data[tcp + 16] = 0;     // Checksum = 0 (simplified)
            data[tcp + 17] = 0;
            data[tcp + 18] = 0;     // Urgent pointer = 0
            data[tcp + 19] = 0;
            // Payload (tcp+20..): already random
        }
    }

    /// <summary>
    /// <b>TcpIPv6</b>: fill-then-patch.
    /// Fully well-formed Ethernet/IPv6/TCP segment. Random addresses, ports,
    /// sequence/ack numbers, and payload. ACK+PSH flags set by default.
    /// TCP checksum is set to 0 for simplicity.
    /// </summary>
    private static void GenerateTcpIPv6(ref Xoroshiro128PlusPlus rng, byte[] data)
    {
        rng.FillBytes(data);

        // ── Ethernet header (0–13) ──
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(12), EtherTypeIPv6);

        int ip = EthHeaderSize;
        int tcp = ip + IPv6HeaderSize;
        ushort payloadLength = (ushort)(data.Length - ip - IPv6HeaderSize); // bytes

        // ── IPv6 header ──
        data[ip] = (byte)((data[ip] & 0x0F) | 0x60);
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(ip + 4), payloadLength);
        data[ip + 6] = IpProtoTcp;
        data[ip + 7] = 64;

        // ── TCP header ──
        if (data.Length >= tcp + TcpHeaderSize)
        {
            data[tcp + 12] = 0x50;
            data[tcp + 13] = 0x18;  // ACK + PSH
            data[tcp + 16] = 0;
            data[tcp + 17] = 0;
            data[tcp + 18] = 0;
            data[tcp + 19] = 0;
        }
    }

    // ─── Utility helpers ─────────────────────────────────────────────────────

    /// <summary>
    /// Computes the one's-complement checksum of a 20-byte IPv4 header
    /// located at <paramref name="offset"/> inside <paramref name="buffer"/>.
    /// The checksum field (bytes 10–11 of the header) must be zeroed before calling.
    /// </summary>
    private static ushort CalculateIPv4Checksum(byte[] buffer, int offset)
    {
        // Validate that the 20-byte IPv4 header fits in the buffer
        if (buffer.Length < offset + IPv4HeaderSize)
        {
            return 0;
        }

        uint sum = 0;
        // Sum 10 × 16-bit big-endian words (20-byte fixed header)
        for (int i = 0; i < 10; i++)
        {
            sum += (uint)(buffer[offset + (i * 2)] << 8 | buffer[offset + (i * 2) + 1]);
        }
        // Fold 32-bit carry into 16 bits
        while (sum >> 16 != 0)
        {
            sum = (sum & 0xFFFF) + (sum >> 16);
        }
        return (ushort)~sum;
    }

    /// <summary>
    /// Returns the minimum valid frame size for the specified <paramref name="mode"/>,
    /// ensuring the generated frame always has enough bytes for all required headers.
    /// The returned value is the greater of <paramref name="configuredMin"/> and the
    /// hard minimum for the mode.
    /// </summary>
    private static int MinSizeForMode(RandomFrameMode mode, int configuredMin)
    {
        int modeMin = mode switch
        {
            RandomFrameMode.FullRandom => 1,
            RandomFrameMode.Ethernet => EthHeaderSize,
            RandomFrameMode.IPv4 => EthHeaderSize + IPv4HeaderSize,
            RandomFrameMode.IPv6 => EthHeaderSize + IPv6HeaderSize,
            RandomFrameMode.UdpIPv4 => EthHeaderSize + IPv4HeaderSize + UdpHeaderSize,
            RandomFrameMode.UdpIPv6 => EthHeaderSize + IPv6HeaderSize + UdpHeaderSize,
            RandomFrameMode.TcpIPv4 or RandomFrameMode.TcpStreamIPv4
                                       => EthHeaderSize + IPv4HeaderSize + TcpHeaderSize,
            RandomFrameMode.TcpIPv6 or RandomFrameMode.TcpStreamIPv6
                                       => EthHeaderSize + IPv6HeaderSize + TcpHeaderSize,
            RandomFrameMode.Can => SocketCanHeaderSize + CanClassicDataSize,  // fixed 16 bytes
            RandomFrameMode.CanFd => SocketCanHeaderSize + 1,                   // min 1 data byte
            _ => 1,
        };
        return Math.Max(configuredMin, modeMin);
    }

    /// <summary>
    /// Derives an unpredictable 64-bit seed from system entropy:
    /// current UTC time in nanoseconds XOR-ed with the process ID shifted to the high 32 bits.
    /// </summary>
    private static ulong DeriveEntropySeed()
    {
        long nanos = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() * 1_000_000L;
        ulong pid = (ulong)Environment.ProcessId;
        return (ulong)nanos ^ (pid << 32);
    }

    /// <summary>Returns the current UTC time as a <see cref="Timestamp"/>.</summary>
    private static Timestamp CurrentTimestamp()
    {
        long nanos = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() * 1_000_000L;
        return new Timestamp(nanos);
    }

    /// <summary>Builds a human-readable name from the options when no explicit name is provided.</summary>
    private static string BuildDefaultName(RandomSourceOptions options) =>
        $"random({options.Mode}, count={options.FrameCount}, seed={options.Seed?.ToString() ?? "entropy"})";

    /// <summary>
    /// Validates the supplied options at construction time so invalid configurations surface
    /// immediately rather than at the first <see cref="Start"/> call. Mirrors the eager
    /// validation done by <c>BlfSource.Open</c> and <c>PcapSource.Open</c>.
    /// </summary>
    /// <exception cref="ArgumentNullException"><paramref name="options"/> is null.</exception>
    /// <exception cref="ArgumentOutOfRangeException">An option is outside its allowed range.</exception>
    private static RandomSourceOptions ValidateOptions(RandomSourceOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        options.Validate();
        return options;
    }

    /// <summary>
    /// Returns the <see cref="LinkType"/> appropriate for the given <paramref name="mode"/>.
    /// CAN and CAN FD modes use <see cref="LinkType.CanSocketcan"/>; all others use
    /// <see cref="LinkType.Ethernet"/>.
    /// </summary>
    private static LinkType LinkTypeForMode(RandomFrameMode mode) =>
        IsCanMode(mode) ? LinkType.CanSocketcan : LinkType.Ethernet;

    /// <summary>
    /// Returns <c>true</c> when <paramref name="mode"/> generates CAN bus frames
    /// instead of Ethernet frames.
    /// </summary>
    private static bool IsCanMode(RandomFrameMode mode) =>
        mode is RandomFrameMode.Can or RandomFrameMode.CanFd;

    #endregion
}
