// Copyright © 2026 DevAM. All rights reserved. Licensed under MIT license. See license in the repository root for license information.

namespace NetworkInspector.Sources.Random;

/// <summary>
/// Specifies the type of synthetic random frames generated by <see cref="RandomFrameSource"/>.
/// </summary>
public enum RandomFrameMode
{
    #region Enum Values

    /// <summary>
    /// Generate completely random bytes with no protocol structure.
    /// The fastest mode — only a single <see cref="Xoroshiro128PlusPlus.FillBytes"/> call.
    /// </summary>
    FullRandom = 0,

    /// <summary>
    /// Generate valid Ethernet frames.
    /// MAC destination, MAC source, and EtherType are all random.
    /// Payload bytes are random.
    /// </summary>
    Ethernet = 1,

    /// <summary>
    /// Generate Ethernet frames encapsulating IPv4 packets with random payloads.
    /// Fills the entire buffer with random bytes, then patches the required IPv4
    /// header fields (EtherType, version/IHL, total length, DF flag, TTL, checksum).
    /// The protocol field is left random; use <see cref="UdpIPv4"/> for well-formed UDP.
    /// </summary>
    IPv4 = 2,

    /// <summary>
    /// Generate Ethernet frames encapsulating IPv6 packets with random payloads.
    /// Fills the entire buffer with random bytes, then patches the required IPv6
    /// header fields (EtherType, version nibble, payload length, hop limit).
    /// The next-header field is left random; use <see cref="UdpIPv6"/> for well-formed UDP.
    /// </summary>
    IPv6 = 3,

    /// <summary>
    /// Generate Ethernet/IPv4/UDP frames with random addresses, ports, and payload.
    /// Fully well-formed: correct EtherType, IP version/IHL/length/protocol/checksum,
    /// and UDP length.  UDP checksum is set to zero (optional in IPv4).
    /// </summary>
    UdpIPv4 = 4,

    /// <summary>
    /// Generate Ethernet/IPv6/UDP frames with random addresses, ports, and payload.
    /// Fully well-formed: correct EtherType, IPv6 version/payload length/next-header,
    /// and UDP length.  UDP checksum is set to zero.
    /// </summary>
    UdpIPv6 = 5,

    /// <summary>
    /// Generate classic CAN 2.0 frames in SocketCAN format.
    /// Each frame has a random CAN ID (11-bit or 29-bit extended), a random DLC (0–8),
    /// and random data bytes.  The frame is always 16 bytes (8-byte header + 8-byte data).
    /// Uses <see cref="LinkType.CanSocketcan"/>.
    /// </summary>
    Can = 6,

    /// <summary>
    /// Generate CAN FD frames in SocketCAN format.
    /// Each frame has a random CAN ID (11-bit or 29-bit extended), a random DLC (0–15)
    /// with the corresponding FD data length (up to 64 bytes), BRS and FDF flags set,
    /// and random data bytes.  Uses <see cref="LinkType.CanSocketcan"/>.
    /// </summary>
    CanFd = 7,

    /// <summary>
    /// Generate Ethernet/IPv4/TCP frames with random addresses, ports, sequence numbers, and payload.
    /// Fully well-formed: correct EtherType, IP version/IHL/length/protocol/checksum,
    /// and TCP data offset/flags/checksum. Individual segments with no stream tracking.
    /// </summary>
    TcpIPv4 = 8,

    /// <summary>
    /// Generate Ethernet/IPv6/TCP frames with random addresses, ports, sequence numbers, and payload.
    /// Fully well-formed: correct EtherType, IPv6 version/payload length/next-header,
    /// and TCP data offset/flags/checksum. Individual segments with no stream tracking.
    /// </summary>
    TcpIPv6 = 9,

    /// <summary>
    /// Generate full TCP connections (SYN → data → FIN) over IPv4.
    /// Stateless rule-based generation via <see cref="TcpStreamFrameBuilder"/> with
    /// configurable stream count, segments per stream, and handshake/teardown inclusion.
    /// Any frame is independently reproducible by index from the master seed.
    /// </summary>
    TcpStreamIPv4 = 10,

    /// <summary>
    /// Generate full TCP connections (SYN → data → FIN) over IPv6.
    /// Stateless rule-based generation via <see cref="TcpStreamFrameBuilder"/> with
    /// configurable stream count, segments per stream, and handshake/teardown inclusion.
    /// Any frame is independently reproducible by index from the master seed.
    /// </summary>
    TcpStreamIPv6 = 11,

    #endregion
}
