<!-- Copyright © 2026 DevAM. Licensed under the MIT License. See LICENSE in the repository root. -->
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetworkInspector.Generators\NetworkInspector.Generators.csproj" />
  </ItemGroup>
</Project>
