<!-- Copyright © 2026 DevAM. Licensed under the MIT License. See LICENSE in the repository root. -->
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="ZeroAlloc" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetworkInspector.Core\NetworkInspector.Core.csproj" />
    <ProjectReference Include="..\NetworkInspector.Protocols\NetworkInspector.Protocols.csproj" />
  </ItemGroup>
</Project>
