// Copyright © 2026 DevAM. Licensed under the MIT License. See LICENSE in the repository root.

using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using NetworkInspector.Generators.Models;

namespace NetworkInspector.Generators;

/// <summary>
/// Source-text emission for <see cref="ProtocolGenerator"/>. Owns the <see cref="StringBuilder"/>-based
/// code writers and the identifier-naming utilities used by the generated partial class.
/// </summary>
public sealed partial class ProtocolGenerator
{
    #region Source Output

    /// <summary>Reports diagnostics and, when there are no errors, emits the generated source.</summary>
    private static void Execute(SourceProductionContext context, ProtocolInfo info)
    {
        foreach (DiagnosticInfo diag in info.Diagnostics)
        {
            context.ReportDiagnostic(diag.ToDiagnostic(info.ClassLocation.ToLocation()));
        }

        bool hasErrors = info.Diagnostics.Any(static d => d.Descriptor.DefaultSeverity == DiagnosticSeverity.Error);
        if (hasErrors)
        {
            return;
        }

        string source = GenerateSource(info);

        // Include the namespace in the HintName to prevent GEN001 collisions when two
        // protocol classes share the same simple class name but differ in namespace.
        string hintName = $"{info.Namespace.Replace('.', '_')}_{info.ClassName}.g.cs";
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    #endregion

    #region Source Emission

    /// <summary>Generates the partial class source code for a protocol.</summary>
    private static string GenerateSource(ProtocolInfo info)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Copyright \u00a9 2026 DevAM. Licensed under the MIT License. See LICENSE in the repository root.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();

        // [GeneratedCode] and [ExcludeFromCoverage] ensure tooling skips the generated boilerplate.
        sb.AppendLine($"[{_GloGeneratedCode}(\"NetworkInspector.Generators.ProtocolGenerator\", \"{_GeneratorVersion}\")]");
        sb.AppendLine($"[{_GloExcludeFromCoverage}]");
        sb.AppendLine($"partial class {info.ClassName}");
        sb.AppendLine("{");

        // Protocol name constants — user strings escaped for C# and XML doc contexts.
        sb.AppendLine($"    /// <summary>Stable machine-readable protocol identifier.</summary>");
        sb.AppendLine($"    /// <remarks>This constant is the canonical identity of this protocol.");
        sb.AppendLine($"    /// Cross-protocol code, filter expressions, and persisted data must");
        sb.AppendLine($"    /// reference this constant rather than a raw string literal so that any");
        sb.AppendLine($"    /// future rename is caught at compile time. The value is guaranteed not to");
        sb.AppendLine($"    /// change for a given protocol implementation.</remarks>");
        sb.AppendLine($"    public const string ProtocolName = \"{EscapeString(info.ProtocolName)}\";");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Human-readable display name for UI surfaces.</summary>");
        sb.AppendLine($"    /// <remarks>This value is intended for display only and is not a stability");
        sb.AppendLine($"    /// contract. It may change across releases as display requirements evolve.");
        sb.AppendLine($"    /// Do not use it in machine-readable comparisons or persisted data;");
        sb.AppendLine($"    /// use <see cref=\"ProtocolName\"/> instead.</remarks>");
        sb.AppendLine($"    public const string ProtocolUiName = \"{EscapeString(info.UiName)}\";");
        sb.AppendLine();

        // Index group name constants
        if (info.IndexGroups.Length > 0)
        {
            foreach (string group in info.IndexGroups)
            {
                string constName = IndexGroupConstantName(group);
                sb.AppendLine($"    /// <summary>Index group name constant for &quot;{EscapeXmlDoc(group)}&quot;.</summary>");
                sb.AppendLine($"    private const string {constName} = \"{EscapeString(group)}\";");
            }
            sb.AppendLine();
        }

        // Protocol table name constants
        if (info.ProtocolTables.Length > 0)
        {
            foreach (ProtocolTableInfo table in info.ProtocolTables)
            {
                string constName = TableNameConstantName(table.Name);
                sb.AppendLine($"    /// <summary>Dispatch table name constant for &quot;{EscapeXmlDoc(table.Name)}&quot;.</summary>");
                sb.AppendLine($"    /// <remarks>This constant is the cross-protocol dispatch contract for this table.");
                sb.AppendLine($"    /// Other protocols registering into or resolving this table must reference this");
                sb.AppendLine($"    /// constant (not the raw string) to ensure consistency and compile-time safety.</remarks>");
                sb.AppendLine($"    public const string {constName} = \"{EscapeString(table.Name)}\";");
            }
            sb.AppendLine();
        }

        // IProtocol.Name and UiName
        sb.AppendLine($"    /// <inheritdoc />");
        sb.AppendLine($"    public string Name => ProtocolName;");
        sb.AppendLine();
        sb.AppendLine($"    /// <inheritdoc />");
        sb.AppendLine($"    public string UiName => ProtocolUiName;");
        sb.AppendLine();

        if (info.Description is not null)
        {
            sb.AppendLine($"    /// <inheritdoc />");
            sb.AppendLine($"    public string Description => \"{EscapeString(info.Description)}\";");
            sb.AppendLine();
        }

        // ProtocolId backing field. Suppress CS0414 because individual protocols may or may not
        // call RecordProtocolPresence(_ProtocolId) in their hand-written partial code.
        sb.AppendLine($"#pragma warning disable CS0414 // Assigned but value may not be read in all protocol implementations");
        sb.AppendLine("    /// <summary>Implementation detail: the protocol's unique ID assigned during <see cref=\"RegisterFields\"/>."
            + " Available for handwritten partial methods such as <c>RecordProtocolPresence</c>.</summary>");
        sb.AppendLine($"    private {_GloProtocolId} _ProtocolId;");
        sb.AppendLine($"#pragma warning restore CS0414");
        sb.AppendLine();

        // Index group ID fields
        foreach (string group in info.IndexGroups)
        {
            string fieldName = IndexGroupFieldName(group);
            sb.AppendLine($"    /// <summary>Index group ID for &quot;{EscapeXmlDoc(group)}&quot;.</summary>");
            sb.AppendLine($"    private {_GloIndexGroupId} {fieldName};");
        }
        if (info.IndexGroups.Length > 0)
        {
            sb.AppendLine();
        }

        // RegisterFields method
        GenerateRegisterFieldsMethod(sb, info);

        // Public accessors for protocol tables
        foreach (ProtocolTableInfo table in info.ProtocolTables)
        {
            string propName = TablePropertyName(table.FieldName);
            sb.AppendLine($"    /// <summary>The {EscapeXmlDoc(table.UiName)} dispatch table ID for sub-protocol registration.</summary>");
            sb.AppendLine($"    public {_GloProtocolTableId} {propName} => {table.FieldName};");
            sb.AppendLine();
        }

        GenerateOnStartMethod(sb);
        GenerateOnShutdownMethod(sb);

        // Partial hook declarations
        sb.AppendLine("    /// <summary>Called at the end of RegisterFields, after all fields, tables, settings, and dispatch entries are registered"
            + " and setting values are loaded into backing fields. Use this hook for config-driven setup (loading config files,"
            + " building lookup dictionaries, registering additional dispatch entries via WhenProtocolTableRegistered,"
            + " resolving cross-protocol field IDs via WhenFieldRegistered). Anything that does not require the frozen Stack"
            + " belongs here, not in OnStartCustom.</summary>");
        sb.AppendLine($"    partial void RegisterFieldsCustom({_GloIStackBuilder} builder, {_GloProtocolId} protocolId);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Called after the stack is built and frozen. Use this hook only for setup that requires the frozen Stack"
            + " (e.g., pre-bound ParseDelegate caches obtained via stack.ResolveParseDelegate)."
            + " Config loading and dispatch registration belong in RegisterFieldsCustom instead.</summary>");
        sb.AppendLine($"    partial void OnStartCustom({_GloStack} stack);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Called before shutdown cleanup. Override in the hand-written partial class to add custom shutdown logic.</summary>");
        sb.AppendLine($"    partial void OnShutdownCustom({_GloStack} stack);");
        sb.AppendLine();

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>Emits <c>RegisterFields</c>, including index groups, fields, dispatch tables, settings and dispatch registrations.</summary>
    private static void GenerateRegisterFieldsMethod(StringBuilder sb, ProtocolInfo info)
    {
        sb.AppendLine("    /// <summary>Registers all fields, dispatch tables, index groups, and settings with the stack builder.</summary>");
        sb.AppendLine($"    public void RegisterFields({_GloIStackBuilder} builder, {_GloProtocolId} protocolId)");
        sb.AppendLine("    {");
        sb.AppendLine("        _ProtocolId = protocolId;");
        sb.AppendLine();

        // Index groups
        if (info.IndexGroups.Length > 0)
        {
            sb.AppendLine("        // Resolve index groups");
            foreach (string group in info.IndexGroups)
            {
                string fieldName = IndexGroupFieldName(group);
                string constName = IndexGroupConstantName(group);
                sb.AppendLine($"        {fieldName} = builder.GetOrCreateIndexGroup({constName});");
            }
            sb.AppendLine();
        }

        // Field registrations
        if (info.Fields.Length > 0)
        {
            sb.AppendLine("        // Register fields");
            foreach (FieldInfo field in info.Fields)
            {
                if (field.IndexGroup is not null)
                {
                    string groupConst = IndexGroupConstantName(field.IndexGroup);
                    string desc = field.Description is not null ? $", \"{EscapeString(field.Description)}\"" : "";
                    sb.AppendLine(
                        $"        {field.FieldName} = builder.RegisterFieldInGroup(protocolId, \"{EscapeString(field.Name)}\","
                        + $" \"{EscapeString(field.UiName)}\", {field.FieldType}, {groupConst}{desc});");
                }
                else
                {
                    string desc = field.Description is not null ? $", \"{EscapeString(field.Description)}\"" : "";
                    sb.AppendLine(
                        $"        {field.FieldName} = builder.RegisterField(protocolId, \"{EscapeString(field.Name)}\","
                        + $" \"{EscapeString(field.UiName)}\", {field.FieldType}{desc});");
                }
            }
            sb.AppendLine();
        }

        // Protocol table registrations
        if (info.ProtocolTables.Length > 0)
        {
            sb.AppendLine("        // Register protocol dispatch tables");
            foreach (ProtocolTableInfo table in info.ProtocolTables)
            {
                string tableConst = TableNameConstantName(table.Name);
                string desc = table.Description is not null ? $", \"{EscapeString(table.Description)}\"" : "";
                sb.AppendLine(
                    $"        {table.FieldName} = builder.RegisterProtocolTable({tableConst},"
                    + $" \"{EscapeString(table.UiName)}\", {_GloTableKeyType}.{table.KeyType}{desc});");
            }
            sb.AppendLine();
        }

        // External table resolution (deferred via WhenProtocolTableRegistered)
        if (info.UsesTables.Length > 0)
        {
            sb.AppendLine("        // Resolve external protocol tables");
            foreach (UsesTableInfo usesTable in info.UsesTables)
            {
                sb.AppendLine($"        builder.WhenProtocolTableRegistered(\"{EscapeString(usesTable.TableName)}\", id => {usesTable.FieldName} = id);");
            }
            sb.AppendLine();
        }

        // Setting registrations
        if (info.Settings.Length > 0)
        {
            sb.AppendLine("        // Register settings via ref struct facade");
            sb.AppendLine($"        {_GloSettingsRegistrar} settings = builder.SettingsRegistrar;");
            foreach (SettingInfo setting in info.Settings)
            {
                string desc = setting.Description is not null ? $", description: \"{EscapeString(setting.Description)}\"" : "";
                string minMax = "";
                if (setting.Min is not null)
                {
                    minMax += $", min: {setting.Min}";
                }
                if (setting.Max is not null)
                {
                    minMax += $", max: {setting.Max}";
                }

                switch (setting.SettingType)
                {
                    case "Bool":
                        sb.AppendLine(
                            $"        settings.RegisterBoolSetting(\"{EscapeString(setting.Name)}\","
                            + $" \"{EscapeString(setting.UiName)}\", \"{EscapeString(setting.GroupName)}\","
                            + $" {setting.DefaultValue}{desc});");
                        break;
                    case "String":
                        sb.AppendLine(
                            $"        settings.RegisterStringSetting(\"{EscapeString(setting.Name)}\","
                            + $" \"{EscapeString(setting.UiName)}\", \"{EscapeString(setting.GroupName)}\","
                            + $" \"{EscapeString(setting.DefaultValue)}\"{desc});");
                        break;
                    case "F64":
                        sb.AppendLine(
                            $"        settings.RegisterF64Setting(\"{EscapeString(setting.Name)}\","
                            + $" \"{EscapeString(setting.UiName)}\", \"{EscapeString(setting.GroupName)}\","
                            + $" {setting.DefaultValue}{minMax}{desc});");
                        break;
                    case "U64":
                        sb.AppendLine(
                            $"        settings.RegisterU64Setting(\"{EscapeString(setting.Name)}\","
                            + $" \"{EscapeString(setting.UiName)}\", \"{EscapeString(setting.GroupName)}\","
                            + $" {setting.DefaultValue}{minMax}{desc});");
                        break;
                    case "I64":
                        sb.AppendLine(
                            $"        settings.RegisterI64Setting(\"{EscapeString(setting.Name)}\","
                            + $" \"{EscapeString(setting.UiName)}\", \"{EscapeString(setting.GroupName)}\","
                            + $" {setting.DefaultValue}{minMax}{desc});");
                        break;
                    case "Bytes":
                        {
                            // Emit literal byte array from pre-validated DefaultHex string to avoid runtime parsing.
                            string bytesDefault = string.IsNullOrEmpty(setting.DefaultValue)
                                ? "global::System.Array.Empty<byte>()"
                                : HexToByteArrayLiteral(setting.DefaultValue);
                            sb.AppendLine(
                                $"        settings.RegisterBytesSetting(\"{EscapeString(setting.Name)}\","
                                + $" \"{EscapeString(setting.UiName)}\", \"{EscapeString(setting.GroupName)}\","
                                + $" {bytesDefault}{desc});");
                            break;
                        }
                    case "Enum":
                        {
                            // setting.EnumValues holds pre-validated, pre-formatted C# tuple content from ExtractEnumSettingInfo.
                            string enumPairs = setting.EnumValues ?? "";
                            sb.AppendLine(
                                $"        settings.RegisterEnumSetting(\"{EscapeString(setting.Name)}\","
                                + $" \"{EscapeString(setting.UiName)}\", \"{EscapeString(setting.GroupName)}\","
                                + $" {setting.DefaultValue}, {_GloEnumMetadata}.FromPairs("
                                + $"new (string, ulong)[] {{ {enumPairs} }}){desc});");
                            break;
                        }
                }
            }
            sb.AppendLine();
        }

        // Table registrations (dispatch registration calls)
        if (info.TableRegistrations.Length > 0)
        {
            sb.AppendLine("        // Register in dispatch tables");
            foreach (TableRegistration reg in info.TableRegistrations)
            {
                switch (reg.KeyType)
                {
                    case "U64":
                        sb.AppendLine($"        builder.RegisterParserInU64TableByName(\"{EscapeString(reg.Table)}\", {reg.U64Key}UL, protocolId);");
                        break;
                    case "String":
                        sb.AppendLine(
                            $"        builder.RegisterParserInStringTableByName(\"{EscapeString(reg.Table)}\","
                            + $" \"{EscapeString(reg.StringKey!)}\", protocolId);");
                        break;
                    case "Bool":
                        sb.AppendLine(
                            $"        builder.RegisterParserInBoolTableByName(\"{EscapeString(reg.Table)}\","
                            + $" {reg.BoolKey.ToString().ToLowerInvariant()}, protocolId);");
                        break;
                    case "Bytes":
                        // Emit a literal byte array rather than a runtime Convert call for reliability and clarity.
                        sb.AppendLine(
                            $"        builder.RegisterParserInBytesTableByName(\"{EscapeString(reg.Table)}\","
                            + $" new {_GloBytesKey}({HexToByteArrayLiteral(reg.BytesKey!)}), protocolId);");
                        break;
                    case "Any":
                        sb.AppendLine($"        builder.RegisterParserInAnyTableByName(\"{EscapeString(reg.Table)}\", protocolId);");
                        break;
                }
            }
            sb.AppendLine();
        }

        // Load setting values into backing fields so RegisterFieldsCustom sees them populated.
        if (info.Settings.Length > 0)
        {
            sb.AppendLine("        // Load setting values into backing fields");
            EmitSettingLoadCode(sb, info);
            sb.AppendLine();
        }

        // Custom hook for config-driven registration (no-op if not implemented).
        sb.AppendLine("        RegisterFieldsCustom(builder, protocolId);");

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits per-setting load code that copies each setting's current value from the
    /// <c>builder.Settings</c> manager into its backing field. Called at the end of
    /// <c>RegisterFields</c> so that <c>RegisterFieldsCustom</c> sees populated
    /// backing fields before the stack is frozen.
    /// </summary>
    private static void EmitSettingLoadCode(StringBuilder sb, ProtocolInfo info)
    {
        // EnumSetting uses GetU64Setting because GetEnumSetting (which returns (string, ulong)?) is not
        // on the IReadOnlySettingsManager interface. Both methods read the same underlying ulong storage.
        foreach (SettingInfo setting in info.Settings)
        {
            switch (setting.SettingType)
            {
                case "Bool":
                    sb.AppendLine(
                        $"        {setting.FieldName} = builder.Settings.GetBoolSetting(\"{EscapeString(setting.Name)}\")"
                        + $" ?? {setting.DefaultValue};");
                    break;
                case "String":
                    sb.AppendLine(
                        $"        {setting.FieldName} = builder.Settings.GetStringSetting(\"{EscapeString(setting.Name)}\")"
                        + $" ?? \"{EscapeString(setting.DefaultValue)}\";");
                    break;
                case "F64":
                    sb.AppendLine($"        {setting.FieldName} = builder.Settings.GetF64Setting(\"{EscapeString(setting.Name)}\") ?? {setting.DefaultValue};");
                    break;
                case "U64":
                    sb.AppendLine($"        {setting.FieldName} = builder.Settings.GetU64Setting(\"{EscapeString(setting.Name)}\") ?? {setting.DefaultValue};");
                    break;
                case "I64":
                    sb.AppendLine($"        {setting.FieldName} = builder.Settings.GetI64Setting(\"{EscapeString(setting.Name)}\") ?? {setting.DefaultValue};");
                    break;
                case "Bytes":
                    {
                        string bytesDefault = string.IsNullOrEmpty(setting.DefaultValue)
                            ? "global::System.Array.Empty<byte>()"
                            : HexToByteArrayLiteral(setting.DefaultValue);
                        sb.AppendLine(
                            $"        {setting.FieldName} = builder.Settings.GetSetting(\"{EscapeString(setting.Name)}\")"
                            + $"?.AsBytes() ?? {bytesDefault};");
                        break;
                    }
                case "Enum":
                    sb.AppendLine($"        {setting.FieldName} = builder.Settings.GetU64Setting(\"{EscapeString(setting.Name)}\") ?? {setting.DefaultValue};");
                    break;
            }
        }
    }

    /// <summary>Emits the boilerplate <c>OnStart(Stack)</c> method that delegates to <c>OnStartCustom</c>.</summary>
    private static void GenerateOnStartMethod(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Calls the optional OnStartCustom hook."
            + " Setting values are already loaded into backing fields by RegisterFields.</summary>");
        sb.AppendLine($"    public void OnStart({_GloStack} stack)");
        sb.AppendLine("    {");
        sb.AppendLine("        OnStartCustom(stack);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>Emits the boilerplate <c>OnShutdown(Stack)</c> method that delegates to <c>OnShutdownCustom</c>.</summary>
    private static void GenerateOnShutdownMethod(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Called on session shutdown. Calls the optional OnShutdownCustom hook.</summary>");
        sb.AppendLine($"    public void OnShutdown({_GloStack} stack)");
        sb.AppendLine("    {");
        sb.AppendLine("        OnShutdownCustom(stack);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    #endregion

    #region Identifier Utilities

    /// <summary>
    /// Escapes a user-supplied string for embedding inside a C# string literal.
    /// Uses <see cref="Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(string, bool)"/> so that all
    /// escape sequences (backslash, quote, newline, null, surrogates, non-printable characters) are handled.
    /// </summary>
    private static string EscapeString(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: false);

    /// <summary>
    /// Escapes characters that are invalid inside XML documentation comment text.
    /// Replaces <c>&amp;</c>, <c>&lt;</c>, and <c>&gt;</c> with their XML entity equivalents.
    /// </summary>
    private static string EscapeXmlDoc(string value)
        => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    /// <summary>
    /// Converts a hex string to a C# byte array literal
    /// (e.g., "01AB" → "new byte[] { 0x01, 0xAB }").
    /// Returns <c>global::System.Array.Empty&lt;byte&gt;()</c> for an empty string.
    /// </summary>
    private static string HexToByteArrayLiteral(string hex)
    {
        if (hex.Length == 0)
        {
            return "global::System.Array.Empty<byte>()";
        }
        StringBuilder sb = new();
        sb.Append("new byte[] { ");
        for (int i = 0; i < hex.Length; i += 2)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }
            sb.Append($"0x{hex[i]}{hex[i + 1]}");
        }
        sb.Append(" }");
        return sb.ToString();
    }

    /// <summary>Converts index group name to a valid field name (e.g., "eth.type" → "_EthTypeGroupId").</summary>
    private static string IndexGroupFieldName(string groupName)
    {
        // Split by dots, capitalise each segment, then append "GroupId".
        string[] parts = groupName.Split('.');
        StringBuilder sb = new();
        sb.Append('_');
        foreach (string part in parts)
        {
            if (part.Length > 0)
            {
                sb.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1)
                {
                    sb.Append(part.Substring(1));
                }
            }
        }
        sb.Append("GroupId");
        return sb.ToString();
    }

    /// <summary>Converts table field name to a property name (e.g., "_EtherTypeTableId" → "EtherTypeTableId").</summary>
    private static string TablePropertyName(string fieldName)
    {
        // Remove leading underscore
        if (fieldName.StartsWith("_", StringComparison.Ordinal))
        {
            return fieldName.Substring(1);
        }
        return fieldName;
    }

    /// <summary>
    /// Converts a dotted name to a PascalCase C# identifier (e.g., "eth.type" → "EthType").
    /// If the result starts with a digit, a leading underscore is prepended to ensure a valid C# identifier.
    /// </summary>
    private static string DottedNameToPascalCase(string name)
    {
        StringBuilder sb = new();
        foreach (string part in name.Split('.'))
        {
            if (part.Length == 0)
            {
                continue;
            }
            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
            {
                sb.Append(part.Substring(1));
            }
        }

        string result = sb.ToString();
        return result.Length > 0 && char.IsDigit(result[0]) ? "_" + result : result;
    }

    /// <summary>Converts an index group name to a constant name (e.g., "eth.type" → "IndexGroupEthType").</summary>
    private static string IndexGroupConstantName(string groupName)
        => "IndexGroup" + DottedNameToPascalCase(groupName);

    /// <summary>Converts a table name to a constant name (e.g., "eth.type" → "TableNameEthType").</summary>
    private static string TableNameConstantName(string tableName)
        => "TableName" + DottedNameToPascalCase(tableName);

    #endregion
}