// Copyright © 2026 DevAM. All rights reserved. Licensed under MIT license. See license in the repository root for license information.

namespace NetworkInspector.Protocols;

/// <summary>
/// ZeroAlloc entry point for the Protocols project.
/// The source generator creates optimized overloads of <see cref="ZeroAllocBase.String"/>,
/// <see cref="ZeroAllocBase.Utf8"/>, and related methods based on call-site argument types,
/// eliminating intermediate <c>ToString()</c> allocations.
/// </summary>
/// <remarks>
/// Usage: <c>ZA.String("prefix: ", address, ", suffix")</c> — ZeroAlloc writes each
/// argument directly into a thread-static buffer using <c>ISpanFormattable.TryFormat</c>,
/// returning a <see cref="TempString"/> that converts to <c>string</c> with one allocation.
/// </remarks>
// CA1812: This class appears unused because all members are static and generated
//         by the ZeroAlloc source generator — the analyzer cannot see generated code.
[SuppressMessage("Performance", "CA1812",
    Justification = "ZeroAlloc partial class: static API members are generated by the source generator.")]
internal sealed partial class ZA : ZeroAllocBase
{
}
