<!-- Copyright © 2026 DevAM. Licensed under the MIT License. See LICENSE in the repository root. -->
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\NetworkInspector.Exporters\NetworkInspector.Exporters.csproj" />
    <ProjectReference Include="..\NetworkInspector.Exporters.DuckDb\NetworkInspector.Exporters.DuckDb.csproj" />
    <ProjectReference Include="..\NetworkInspector.Core\NetworkInspector.Core.csproj" />
    <ProjectReference Include="..\NetworkInspector.Protocols\NetworkInspector.Protocols.csproj" />
    <ProjectReference Include="..\NetworkInspector.Sources\NetworkInspector.Sources.csproj" />
    <ProjectReference Include="..\NetworkInspector.Testing.Tshark\NetworkInspector.Testing.Tshark.csproj" />
  </ItemGroup>
</Project>
